### ISSUE TITLE
Lack of source

### ISSUE THREAD

**Issue by DarkJoker360** [OpenKirin/android_device_huawei_alice#5]
Hello I m waiting of new fixes since last N update, when I can expect to see the new stuff?
The stuff is:

-DT2W fully working
-GPS with 3D fix like in RROS
-BT fully working like Aospa/RROS
-Kernel 3.10.108
-DeepSleep fixed

**Comment by 4PERTURE** [comment]
@DarkJoker360 the device tree doesnt lack source, you just need to apply meticulus patches, the gps patch that surdu posted in my thread, and try the other kernel source for hi6250

**Comment by DarkJoker360** [comment]
Yes I know all stuff, now it s missing dt2w and kernel 3.10.108

**Comment by Huawei-Dev** [comment]
As far as I remember the implementation of d2tw on this device was very simple compared to other devices, may be among the simplest. 
Once you know your kernel touchscreen driver for your device, you can do something similar to what is on this device https://github.com/LineageOS/android_device_huawei_kiwi 
You need only your custom power hal in order to enable dt2w ... but you can make your own one easily by following qcom power implementation 
That's all I did to implement dt2w on this device, unfortunately I didn't save the device tree source with dt2w implementation .
Good luck !

**Comment by Huawei-Dev** [comment]
You need to check also kernel source for kiwi device to see what was changed in order to enable dt2w, and later you need to add cyttsp5_mt.kl
Check this commit : https://github.com/LineageOS/android_device_huawei_kiwi/commit/e2017b6ffccf16c136fbbcb85b33cfc6ae112867#diff-cf3c16306b3cc2df36fa3a59aebde3d4

**Comment by DarkJoker360** [comment]
hello @Huawei-Dev thanks for all your tips !
a question about Oreo, how is RIL implemented as of now?

**Comment by Huawei-Dev** [comment]
There is a issue with modem partitions on this device, seems to be too old for support Oreo RIL implementation. To make the RIL working on Oreo you should use Huawei Oreo RIL blobs ( you can grab it from any Huawei device with Oreo ) - as I did at the time. 
Maybe there is a way to update somehow the modem partitions ( one or more modem related partitions ) but it's a bit risky ! 
I don't know if you'll be able to recovery your device after flashing a new modem partition from other Kirin device, if something goes wrong. 
Basically you need to grab the new modem.img from Huawei Oreo firmware update.app, and in your TWRP you can flash this image over your older modem image in this way : dd if=/sdcard/oreo_modem.img of=/dev/block/platform/hi_mci.0/by-name/modem ( it's just an example, as Alice do not have any partition /modem, instead it have 6 modem related partitions )
I didn't tried to flash something like I described above, because there is 6 modem partitions on Alice device: /modemnvm3, /modemlog, /modemnvm2, /3rdmodem, /3rdmodemnvm, /3rdmodemnvmback and I didn't find a new Huawei device with Oreo support to have the same modem partitions configurations ... and even if there is an identical device, there is no guarantee that after you update all 6 partitions your phone will still work.

**Comment by DarkJoker360** [comment]
Oh, I saw from logs something about denied permissions to ril_rore... It could be the key maybe as ril it is partially working
